# Generated by Django 3.1.6 on 2021-08-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(blank=True, default='', max_length=30)),
                ('back', models.CharField(default='', max_length=30)),
                ('desc', models.TextField(blank=True, default='', max_length=100)),
            ],
        ),
    ]
