# Generated by Django 3.1.6 on 2021-08-09 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_deck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='card',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.card'),
        ),
    ]
