# Generated by Django 3.1.6 on 2021-08-09 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210809_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.card'),
        ),
    ]
