# Generated by Django 3.1.6 on 2021-08-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210809_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='deck',
            field=models.ForeignKey(default='b137ff6d-ac18-474b-b06e-c25bd24bceb8', on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='api.deck'),
        ),
    ]
