# Generated by Django 3.1.6 on 2021-08-16 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210812_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='front',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
